### ISSUE TITLE
SSL unsupported

### ISSUE THREAD

**Issue by olwe1** [Gielert/NoodleJS#19]
Hi, I have an issue with SSL : 

```
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error: 140250520684416:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:ssl/statem/statem_lib.c:1928:

Emitted 'error' event on Client instance at:
    at Connection.<anonymous> (/home/olwe/Documents/code/mumbot/node_modules/noodle.js/src/Client.js:40:18)
    at Connection.emit (events.js:321:20)
    at Connection.EventEmitter.emit (domain.js:485:12)
    at TLSSocket.<anonymous> (/home/olwe/Documents/code/mumbot/node_modules/noodle.js/src/Connection.js:28:22)
    at TLSSocket.emit (events.js:321:20)
    at TLSSocket.EventEmitter.emit (domain.js:485:12)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  library: 'SSL routines',
  function: 'ssl_choose_client_version',
  reason: 'unsupported protocol',
  code: 'ERR_SSL_UNSUPPORTED_PROTOCOL'
}
```

Node.js version : 13.7.0
NPM version : 6.13.6

Is there any documentation on noodle ?
Thanks

**Comment by Serphentas** [comment]
Hey, did you make sure you're not using an SSL/TLS version that's too low ?

**Comment by whopiyush** [comment]
I had the same issue, it's because NodeJS updated the default supported TLS protocol versions to 1.2 since v11. You can fix this by passing a `--tls-min-v1.0` cli option to node - https://nodejs.org/api/cli.html#cli_tls_min_v1_0
